apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
spec:
  selector:
    matchLabels:
      app: binarycalculator
  replicas: 1
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
      - name: binarycalculator
        image: gcr.io/neon-radius-379218/binarycalculator
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: binarycalculator-service
spec:
  selector:
    app: binarycalculator
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
